### PR TITLE
More updates to fix CI

### PR DESCRIPTION
**Pull request by parkr**

### CODE REVIEW

**Comment by parkr** [comment]
@ross Got something started here with an "everything" and a "cloudflare-only" variant. Feel free to take this and run with it, or ignore. I grabbed the `octodns` user on Docker Hub to have it. Happy to send those your way when you're ready for them. Thanks!

**Comment by ross** [comment]
Looks like a good starting point. I can give you access to create repos in the octoDNS org and then full access to it once it's there, if you think it living there makes sense.

Once I'm done with the extracting of providers I'll probably put some time into exploring scripts to help with managing all the repos. Should be possible to use that sort of stuff to help automate the flavors here.

/cc https://github.com/octodns/octodns/pull/835

**Comment by parkr** [comment]
> I can give you access to create repos in the octoDNS org and then full access to it once it's there, if you think it living there makes sense.

Happy to move it over at your leisure. I think it should live in github.com/octodns, personally. How about `octodns/docker`?

> scripts to help with managing all the repos

Yeah, having some way to set the version we want to use for X repo, then propagating that out to the Docker image flavors would be nice. 

> flavors

Thinking more about this, I'm thinking including `octodns` in the image name is superfluous. So each flavor matches the Docker image name without stuttering too much:

- cloudflare flavor: `docker run octodns/cloudflare:version` or `docker run ghcr.io/octodns/docker/cloudflare:version`
- ns1 flavor: `docker run octodns/ns1:version` or `docker run ghcr.io/octodns/docker/ns1:version`
- all flavor (call it 'octodns'): `docker run octodns/octodns:version` or `docker run ghcr.io/octodns/docker/octodns:version`

etc etc

**Comment by ross** [comment]
> Happy to move it over at your leisure. I think it should live in github.com/octodns, personally. How about `octodns/docker`?

👍 . Sent an org invite your way. Once accepted you should be able to move & rename. 

> Thinking more about this, I'm thinking including `octodns` in the image name is superfluous. So each flavor matches the Docker image name without stuttering too much:

👍

**Comment by parkr** [comment]
@ross All transferred, and I added all the rest of the flavors. Versions managed in `all/requirements.txt`.

**Comment by ross** [comment]
> @ross All transferred, and I added all the rest of the flavors. Versions managed in `all/requirements.txt`.

Sweet 🍬 . Did you still want to rename it `docker` or plan to stick with `octodns-docker`?

I have a TODO to keep it in sync with new providers, though I'll probably wait until all of them are extracted and do a single round for now.

**Comment by parkr** [comment]
@ross Feel free to rename! I don't have admin privileges on the repo so I can't. Luckily the Docker Hub secret transferred!

I simplified version management such that you update the version in one requirements.txt file and that's used to generate each flavor. So should be somewhat simple.

**Comment by ross** [comment]
> @ross Feel free to rename! I don't have admin privileges on the repo so I can't. Luckily the Docker Hub secret transferred!

Weird that you can move stuff in w/o admin, but can't rename once it's there, 🤷. Will grant you admin on that repo to do with what you wish.

> I simplified version management such that you update the version in one requirements.txt file and that's used to generate each flavor. So should be somewhat simple.

Nice.

**Pull request merged**
